### ISSUE TITLE
Generate function static values not being inserted.

### ISSUE THREAD

**Issue by AnthonyConklin** [edwardanthony/nestjs-seeder#24] opened 2022-01-24 17:55 UTC
Problem:
```
const data = DataFactory.createForClass(Message).generate(1, {
  body: 'Test this overwrites'
});
// Output { "body": "Exercitationem rerum ab quae libero nobis debitis deleniti iusto aut." }
// Expected { "body": "Test this overwrites" }
```

// message.schema.ts
```
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Date, Document, Types } from 'mongoose';
import { Factory } from 'nestjs-seeder';
import { Chat } from 'src/chats/chat.schema';
import { User } from 'src/users/user.schema';

@Schema()
export class MessageHistory {
  @Prop({ default: '' })
  message: string;

  @Prop({ type: Date, default: Date.now })
  timestamp: Date;
}
// Generate a Mongoose Schema before use as Subdocument
const MessageHistorySchema = SchemaFactory.createForClass(MessageHistory);

@Schema({
  timestamps: true,
  toJSON: {
    virtuals: true
  }
})
export class Message {
  @Prop({ type: String, ref: 'User' })
  user: User;

  @Prop({ type: Types.ObjectId, ref: 'Chat', index: true })
  chat: Chat;

  @Factory((faker) => faker.lorem.sentence())
  @Prop({ default: '' })
  body: string;

  @Prop({ type: Date, default: undefined })
  deletedAt: Date;

  @Prop({ type: [MessageHistorySchema] })
  editHistory: MessageHistory[];
}

export type MessageDocument = Message & Document;

export const MessageSchema = SchemaFactory.createForClass(Message);

MessageSchema.virtual('edited').get(function (this: MessageDocument) {
  return this.editHistory.length > 0;
});
```

**Comment by JeremiahKoeiman** [comment] 2023-12-28 21:29
I have this same problem but with TypeORM.

**Comment by JeremiahKoeiman** [comment] 2023-12-28 21:30
@AnthonyConklin did you find a solution?

**Comment by JeremiahKoeiman** [comment] 2023-12-30 15:21
@AnthonyConklin I have created a fork from this repo [HERE](https://github.com/JeremiahKoeiman/nestjs-seeder) and have an open PR [HERE](https://github.com/edwardanthony/nestjs-seeder/pull/38) and introduced a potential fix for this problem. It works fine with TypeORM, but I haven't tested it with Mongoose (because I don't know how that works). Can you test if this solution also works for you (with Mongoose)?

**Comment by edwardanthony** [comment] 2023-12-30 16:39
@JeremiahKoeiman this is not a bug.

You're able to fill the context with predefined values by passing an object as the second argument to `generate` method.

```ts
const users = DataFactory.createForClass(User).generate(10, {
  zipCode: "10153",
});
```

You're then able to get that predefine value in the `ctx` object that will be provided by the `@Factory` decorator.

```ts
@Schema()
export class User extends Document {
  // If you pass predefined values to the `generate` function, you will be
  // able to access it in the context.
  @Factory((faker, ctx) => `${faker.location.streetAddress()} ${ctx.zipCode}`)
  @Prop({ required: true })
  address: string;
}
```

Remember that this process is not automatic. You need to get it from the `ctx` object to get the predefine values.

**Comment by JeremiahKoeiman** [comment] 2023-12-30 18:45
@edwardanthony will this also work when you have a relationship between 2 entities? I have this example:

```typescript
@Entity()
export class Project {
  @OneToMany(() => Section, (section) => section.project, {
    cascade: true,
    createForeignKeyConstraints: true,
  })
  public sections?: Section[];
}
```

```typescript
@Entity()
export class Section {
  @Factory((_, ctx) => ctx.project)
  @ManyToOne(() => Project, (project) => project.sections)
  public project?: Project;
}
```

```typescript
const generatedProjects = DataFactory.createForClass(Project).generate(5);
const savedProjects = await this.projectRepository.save(generatedProjects);
savedProjects.forEach((project: Project) =>
  DataFactory.createForClass(Section).generate(3, {
    project: project,
  }),
);
```

I've tried what you mentioned above, but it seems like the data passed to the `generate` method is being passed correctly (maybe this is a TypeORM issue?), because when I look in my database the projects table is filled with data, but the section table isn't.

Am I doing something wrong?

**Comment by edwardanthony** [comment] 2023-12-30 19:12
@JeremiahKoeiman  `nestjs-seeder` has absolutely no relation to the database.
All it does that it takes your model class, and generate objects based on your provided model class.

I'll answer this using your example which is one-to-many relationship between project and section:

**1. Define the section model**

```ts
export class Section {
  projectId: number; // you can also put the Project model as data type here
  
  @Factory(faker => faker.lorem.words(2))
  name: string;
}
```

**2. Using the section model, generate section objects** 

```ts
const sections: Section[] = [];

for (const project of projects) {
  // Generate 10 sections
  const generatedSections = DataFactory.createForClass(Section).generate(10);
  
  // Remember, the generated sections are just instances of the section class.
  // So you can modify the property after, it's just normal Javascript object.
  // Here, I'll set the project id to the id of the project in the loop.
  const sectionsAssociatedWithProject = generatedSections.map(section => ({ 
    ...section, 
    projectId: project.id 
  }))
  
  sections.push(...sectionsAssociatedWithProject);
}

// Here you can you use sections variable to insert into any database
// You can use SQL, MongoDB, or anything you like.
```

In the code above, you'll get idea about how to generate multiple sections that belongs to the same project.

**Comment by JeremiahKoeiman** [comment] 2023-12-31 15:12
You're absolutely right and it works! Thank you @edwardanthony. I've closed this [PR](https://github.com/edwardanthony/nestjs-seeder/pull/38)

**Comment by edwardanthony** [comment] 2023-12-31 15:13
Closed. No fix required.

**Closed by edwardanthony** 2023-12-31 15:13 UTC
